swagger-api:
  version: "1.0"

spring:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
# datasource:
#    url: jdbc:h2:mem:h2
#    username: test
#    password: test

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ulab_db
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info